import { FitTrackerData } from '../types';

export const INITIAL_MOCK_DATA: FitTrackerData = {
  profile: {
    id: 'usr_01',
    name: 'Warrior User',
    currentWeightKg: 78.5,
    totalWorkouts: 14,
  },
  templates: [
    {
      id: 'tpl_upper_b',
      title: 'Upper B',
      description: 'Séance haut du corps axée pectoraux, deltoïdes, tirage et bras avec superset.',
      targetMuscles: ['Pectoraux', 'Triceps', 'Épaules', 'Dos', 'Biceps'],
      exercises: [
        {
          id: 'ex_tpl_dips',
          exerciseId: 'dips',
          exerciseName: 'Dips',
          primaryMuscle: 'Pectoraux & Triceps',
          targetMuscles: ['Pectoraux (Bas)', 'Triceps', 'Deltoïde antérieur'],
          restSeconds: 90,
          sets: [
            { id: 's1', setNumber: 1, type: 'normal', weightKg: 0, reps: 12, rir: 2, completed: false, previous: 'Poids de corps x 12' },
            { id: 's2', setNumber: 2, type: 'normal', weightKg: 10, reps: 10, rir: 1, completed: false, previous: '+10kg x 10' },
            { id: 's3', setNumber: 3, type: 'normal', weightKg: 10, reps: 9, rir: 1, completed: false, previous: '+10kg x 9' },
            { id: 's4', setNumber: 4, type: 'normal', weightKg: 10, reps: 8, rir: 0, completed: false, previous: '+10kg x 8' },
          ],
        },
        {
          id: 'ex_tpl_low_fly',
          exerciseId: 'low_cable_fly',
          exerciseName: 'Low Cable Fly',
          primaryMuscle: 'Pectoraux',
          targetMuscles: ['Pectoraux (Haut & Médian)'],
          restSeconds: 75,
          sets: [
            { id: 's5', setNumber: 1, type: 'normal', weightKg: 12.5, reps: 12, rir: 2, completed: false, previous: '12.5kg x 12' },
            { id: 's6', setNumber: 2, type: 'normal', weightKg: 15, reps: 10, rir: 1, completed: false, previous: '15kg x 10' },
            { id: 's7', setNumber: 3, type: 'normal', weightKg: 15, reps: 10, rir: 0, completed: false, previous: '15kg x 10' },
          ],
        },
        {
          id: 'ex_tpl_tirage_h',
          exerciseId: 'tirage_horiz_unilat',
          exerciseName: 'Tirage Horizontal Unilatéral',
          primaryMuscle: 'Grand Dorsal',
          targetMuscles: ['Grand Dorsal', 'Trapèzes moyens', 'Biceps'],
          restSeconds: 90,
          sets: [
            { id: 's8', setNumber: 1, type: 'normal', weightKg: 35, reps: 10, rir: 2, completed: false, previous: '35kg x 10' },
            { id: 's9', setNumber: 2, type: 'normal', weightKg: 40, reps: 9, rir: 1, completed: false, previous: '40kg x 9' },
            { id: 's10', setNumber: 3, type: 'normal', weightKg: 40, reps: 8, rir: 0, completed: false, previous: '40kg x 8' },
          ],
        },
        {
          id: 'ex_tpl_oiseau_poulie',
          exerciseId: 'oiseau_poulie_unilat',
          exerciseName: 'Oiseau à la Poulie Unilatéral',
          primaryMuscle: 'Deltoïde Postérieur',
          targetMuscles: ['Deltoïde postérieur', 'Rhomboïdes'],
          restSeconds: 60,
          supersetGroup: 'Superset A',
          sets: [
            { id: 's11', setNumber: 1, type: 'normal', weightKg: 7.5, reps: 15, rir: 2, completed: false, previous: '7.5kg x 15' },
            { id: 's12', setNumber: 2, type: 'normal', weightKg: 10, reps: 12, rir: 1, completed: false, previous: '10kg x 12' },
            { id: 's13', setNumber: 3, type: 'normal', weightKg: 10, reps: 12, rir: 1, completed: false, previous: '10kg x 12' },
            { id: 's14', setNumber: 4, type: 'normal', weightKg: 10, reps: 10, rir: 0, completed: false, previous: '10kg x 10' },
          ],
        },
        {
          id: 'ex_tpl_elev_lat',
          exerciseId: 'elevations_lat_poulie',
          exerciseName: 'Élévations Latérales Poulie',
          primaryMuscle: 'Deltoïde Latéral',
          targetMuscles: ['Deltoïde latéral (Épaules)'],
          restSeconds: 60,
          supersetGroup: 'Superset A',
          sets: [
            { id: 's15', setNumber: 1, type: 'normal', weightKg: 7.5, reps: 14, rir: 2, completed: false, previous: '7.5kg x 14' },
            { id: 's16', setNumber: 2, type: 'normal', weightKg: 10, reps: 12, rir: 1, completed: false, previous: '10kg x 12' },
            { id: 's17', setNumber: 3, type: 'normal', weightKg: 10, reps: 11, rir: 0, completed: false, previous: '10kg x 11' },
          ],
        },
        {
          id: 'ex_tpl_overhead',
          exerciseId: 'overhead_triceps',
          exerciseName: 'Overhead Extension Triceps',
          primaryMuscle: 'Triceps (Chef long)',
          targetMuscles: ['Triceps (Chef long)', 'Deltoïdes'],
          restSeconds: 75,
          sets: [
            { id: 's18', setNumber: 1, type: 'normal', weightKg: 20, reps: 12, rir: 2, completed: false, previous: '20kg x 12' },
            { id: 's19', setNumber: 2, type: 'normal', weightKg: 24, reps: 10, rir: 1, completed: false, previous: '24kg x 10' },
            { id: 's20', setNumber: 3, type: 'normal', weightKg: 24, reps: 9, rir: 0, completed: false, previous: '24kg x 9' },
          ],
        },
        {
          id: 'ex_tpl_curl_pupitre',
          exerciseId: 'curl_pupitre_halteres',
          exerciseName: 'Curl Pupitre Haltères',
          primaryMuscle: 'Biceps',
          targetMuscles: ['Biceps brachial', 'Brachial antérieur'],
          restSeconds: 90,
          sets: [
            { id: 's21', setNumber: 1, type: 'failure', weightKg: 14, reps: 10, rir: 0, completed: false, previous: '14kg x 10 (Échec)' },
            { id: 's22', setNumber: 2, type: 'failure', weightKg: 14, reps: 8, rir: 0, completed: false, previous: '14kg x 8 (Échec)' },
          ],
        },
      ],
    },
    {
      id: 'tpl_circuit_abdos',
      title: 'Circuit Abdos',
      description: 'Circuit dynamique et statique de 6 exercices pour la sangle abdominale. À répéter 3 fois avec 1m30 - 2m de repos après la planche.',
      targetMuscles: ['Grand Droit', 'Obliques', 'Transverse / Gainage'],
      isCircuit: true,
      circuitRounds: 3,
      restBetweenRoundsSeconds: 105,
      exercises: [
        {
          id: 'ex_ab_1',
          exerciseId: 'crunch',
          exerciseName: 'Crunch',
          primaryMuscle: 'Grand droit de l\'abdomen',
          targetMuscles: ['Grand droit de l\'abdomen (Haut des abdos)'],
          restSeconds: 0,
          sets: [
            { id: 'abs1_1', setNumber: 1, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps' },
            { id: 'abs1_2', setNumber: 2, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps' },
            { id: 'abs1_3', setNumber: 3, type: 'normal', weightKg: 0, reps: 10, rir: 1, completed: false, previous: '10 reps' },
          ],
        },
        {
          id: 'ex_ab_2',
          exerciseId: 'foot_to_foot',
          exerciseName: 'Foot to Foot',
          primaryMuscle: 'Obliques',
          targetMuscles: ['Obliques internes et externes'],
          restSeconds: 0,
          sets: [
            { id: 'abs2_1', setNumber: 1, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps' },
            { id: 'abs2_2', setNumber: 2, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps' },
            { id: 'abs2_3', setNumber: 3, type: 'normal', weightKg: 0, reps: 10, rir: 1, completed: false, previous: '10 reps' },
          ],
        },
        {
          id: 'ex_ab_3',
          exerciseId: 'releve_jambes_bassin',
          exerciseName: 'Relevé de Jambes et de Bassin',
          primaryMuscle: 'Bas des abdos',
          targetMuscles: ['Grand droit (Bas des abdos)', 'Fléchisseurs de hanche'],
          restSeconds: 0,
          sets: [
            { id: 'abs3_1', setNumber: 1, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps' },
            { id: 'abs3_2', setNumber: 2, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps' },
            { id: 'abs3_3', setNumber: 3, type: 'normal', weightKg: 0, reps: 10, rir: 1, completed: false, previous: '10 reps' },
          ],
        },
        {
          id: 'ex_ab_4',
          exerciseId: 'russian_twist',
          exerciseName: 'Russian Twist (Sans poids)',
          primaryMuscle: 'Obliques & Sangle abdominale',
          targetMuscles: ['Obliques', 'Sangle abdominale profonde'],
          restSeconds: 0,
          sets: [
            { id: 'abs4_1', setNumber: 1, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps' },
            { id: 'abs4_2', setNumber: 2, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps' },
            { id: 'abs4_3', setNumber: 3, type: 'normal', weightKg: 0, reps: 10, rir: 1, completed: false, previous: '10 reps' },
          ],
        },
        {
          id: 'ex_ab_5',
          exerciseId: 'planche_lat_dyn',
          exerciseName: 'Planches Latérales Dynamiques',
          primaryMuscle: 'Obliques & Gainage latéral',
          targetMuscles: ['Obliques (par côté)', 'Carré des lombes'],
          restSeconds: 0,
          sets: [
            { id: 'abs5_1', setNumber: 1, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps / côté' },
            { id: 'abs5_2', setNumber: 2, type: 'normal', weightKg: 0, reps: 10, rir: 2, completed: false, previous: '10 reps / côté' },
            { id: 'abs5_3', setNumber: 3, type: 'normal', weightKg: 0, reps: 10, rir: 1, completed: false, previous: '10 reps / côté' },
          ],
        },
        {
          id: 'ex_ab_6',
          exerciseId: 'planche_statique',
          exerciseName: 'Planche Statique',
          primaryMuscle: 'Gainage profond / Transverse',
          targetMuscles: ['Transverse', 'Lombaires', 'Plancher pelvien'],
          restSeconds: 105, // 1 min 30 à 2 min de repos après la planche
          sets: [
            { id: 'abs6_1', setNumber: 1, type: 'normal', weightKg: 0, reps: 45, durationSeconds: 45, rir: 1, completed: false, previous: '45 sec' },
            { id: 'abs6_2', setNumber: 2, type: 'normal', weightKg: 0, reps: 45, durationSeconds: 45, rir: 1, completed: false, previous: '45 sec' },
            { id: 'abs6_3', setNumber: 3, type: 'normal', weightKg: 0, reps: 45, durationSeconds: 45, rir: 0, completed: false, previous: '45 sec' },
          ],
        },
      ],
    },
  ],
  history: [
    {
      id: 'sess_upper_b_aug7',
      title: 'Upper B',
      templateId: 'tpl_upper_b',
      startTime: '2026-08-07T17:30:00.000Z',
      endTime: '2026-08-07T18:45:00.000Z',
      durationSeconds: 4500,
      totalVolumeKg: 3840,
      completedSetsCount: 20,
      totalSetsCount: 20,
      status: 'completed',
      exercises: [
        {
          id: 'ex_hist_1',
          exerciseId: 'dips',
          exerciseName: 'Dips',
          primaryMuscle: 'Pectoraux & Triceps',
          targetMuscles: ['Pectoraux (Bas)', 'Triceps', 'Deltoïde antérieur'],
          restSeconds: 90,
          sets: [
            { id: 'hs1', setNumber: 1, type: 'normal', weightKg: 0, reps: 12, rir: 2, completed: true, completedAt: '2026-08-07T17:35:00.000Z' },
            { id: 'hs2', setNumber: 2, type: 'normal', weightKg: 10, reps: 10, rir: 1, completed: true, completedAt: '2026-08-07T17:38:00.000Z' },
            { id: 'hs3', setNumber: 3, type: 'normal', weightKg: 10, reps: 9, rir: 1, completed: true, completedAt: '2026-08-07T17:41:00.000Z' },
            { id: 'hs4', setNumber: 4, type: 'normal', weightKg: 10, reps: 8, rir: 0, completed: true, completedAt: '2026-08-07T17:44:00.000Z' },
          ],
        },
        {
          id: 'ex_hist_2',
          exerciseId: 'low_cable_fly',
          exerciseName: 'Low Cable Fly',
          primaryMuscle: 'Pectoraux',
          targetMuscles: ['Pectoraux (Haut & Médian)'],
          restSeconds: 75,
          sets: [
            { id: 'hs5', setNumber: 1, type: 'normal', weightKg: 12.5, reps: 12, rir: 2, completed: true, completedAt: '2026-08-07T17:48:00.000Z' },
            { id: 'hs6', setNumber: 2, type: 'normal', weightKg: 15, reps: 10, rir: 1, completed: true, completedAt: '2026-08-07T17:51:00.000Z' },
            { id: 'hs7', setNumber: 3, type: 'normal', weightKg: 15, reps: 10, rir: 0, completed: true, completedAt: '2026-08-07T17:54:00.000Z' },
          ],
        },
      ],
    },
  ],
  measurements: [
    { id: 'm1', date: '2026-08-01', weightKg: 79.0, chestCm: 104, waistCm: 82, bicepsCm: 39 },
    { id: 'm2', date: '2026-08-08', weightKg: 78.5, chestCm: 104.5, waistCm: 81.5, bicepsCm: 39.2 },
  ],
};
