import { FitTrackerData } from '../types';

export const INITIAL_MOCK_DATA: FitTrackerData = {
  profile: {
    id: 'usr_01',
    name: 'Warrior User',
    currentWeightKg: 78.5,
    totalWorkouts: 14,
  },
  templates: [
    {
      id: 'tpl_upper_b',
      title: 'Upper B',
      description: 'Séance haut du corps axée pectoraux, deltoïdes, tirage et bras avec superset.',
      targetMuscles: ['Pectoraux', 'Triceps', 'Épaules', 'Dos', 'Biceps'],
      exercises: [
        {
          id: 'ex_tpl_dips',
          exerciseId: 'dips',
          exerciseName: 'Dips',
          primaryMuscle: 'Pectoraux & Triceps',
          targetMuscles: ['Pectoraux (Bas)', 'Triceps', 'Deltoïde antérieur'],
          restSeconds: 90,
          sets: [
            { id: 's1', setNumber: 1, type: 'normal', weightKg: 0, reps: 12, rir: undefined, completed: false, previous: 'Poids de corps x 12' },
            { id: 's2', setNumber: 2, type: 'normal', weightKg: 10, reps: 10, rir: undefined, completed: false, previous: '+10kg x 10' },
            { id: 's3', setNumber: 3, type: 'normal', weightKg: 10, reps: 9, rir: undefined, completed: false, previous: '+10kg x 9' },
            { id: 's4', setNumber: 4, type: 'normal', weightKg: 10, reps: 8, rir: undefined, completed: false, previous: '+10kg x 8' },
          ],
        },
        {
          id: 'ex_tpl_low_fly',
          exerciseId: 'low_cable_fly',
          exerciseName: 'Low Cable Fly',
          primaryMuscle: 'Pectoraux',
          targetMuscles: ['Pectoraux (Haut & Médian)'],
          restSeconds: 75,
          sets: [
            { id: 's5', setNumber: 1, type: 'normal', weightKg: 12.5, reps: 12, rir: undefined, completed: false, previous: '12.5kg x 12' },
            { id: 's6', setNumber: 2, type: 'normal', weightKg: 15, reps: 10, rir: undefined, completed: false, previous: '15kg x 10' },
            { id: 's7', setNumber: 3, type: 'normal', weightKg: 15, reps: 10, rir: undefined, completed: false, previous: '15kg x 10' },
          ],
        },
        {
          id: 'ex_tpl_tirage_h',
          exerciseId: 'tirage_horiz_unilat',
          exerciseName: 'Tirage Horizontal Unilatéral',
          primaryMuscle: 'Grand Dorsal',
          targetMuscles: ['Grand Dorsal', 'Trapèzes moyens', 'Biceps'],
          restSeconds: 90,
          sets: [
            { id: 's8', setNumber: 1, type: 'normal', weightKg: 35, reps: 10, rir: undefined, completed: false, previous: '35kg x 10' },
            { id: 's9', setNumber: 2, type: 'normal', weightKg: 40, reps: 9, rir: undefined, completed: false, previous: '40kg x 9' },
            { id: 's10', setNumber: 3, type: 'normal', weightKg: 40, reps: 8, rir: undefined, completed: false, previous: '40kg x 8' },
          ],
        },
        {
          id: 'ex_tpl_oiseau_poulie',
          exerciseId: 'oiseau_poulie_unilat',
          exerciseName: 'Oiseau à la Poulie Unilatéral',
          primaryMuscle: 'Deltoïde Postérieur',
          targetMuscles: ['Deltoïde postérieur', 'Rhomboïdes'],
          restSeconds: 60,
          supersetGroup: 'Superset A',
          sets: [
            { id: 's11', setNumber: 1, type: 'normal', weightKg: 7.5, reps: 15, rir: undefined, completed: false, previous: '7.5kg x 15' },
            { id: 's12', setNumber: 2, type: 'normal', weightKg: 10, reps: 12, rir: undefined, completed: false, previous: '10kg x 12' },
            { id: 's13', setNumber: 3, type: 'normal', weightKg: 10, reps: 12, rir: undefined, completed: false, previous: '10kg x 12' },
            { id: 's14', setNumber: 4, type: 'normal', weightKg: 10, reps: 10, rir: undefined, completed: false, previous: '10kg x 10' },
          ],
        },
        {
          id: 'ex_tpl_elev_lat',
          exerciseId: 'elevations_lat_poulie',
          exerciseName: 'Élévations Latérales Poulie',
          primaryMuscle: 'Deltoïde Latéral',
          targetMuscles: ['Deltoïde latéral (Épaules)'],
          restSeconds: 60,
          supersetGroup: 'Superset A',
          sets: [
            { id: 's15', setNumber: 1, type: 'normal', weightKg: 7.5, reps: 14, rir: undefined, completed: false, previous: '7.5kg x 14' },
            { id: 's16', setNumber: 2, type: 'normal', weightKg: 10, reps: 12, rir: undefined, completed: false, previous: '10kg x 12' },
            { id: 's17', setNumber: 3, type: 'normal', weightKg: 10, reps: 11, rir: undefined, completed: false, previous: '10kg x 11' },
          ],
        },
        {
          id: 'ex_tpl_overhead',
          exerciseId: 'overhead_triceps',
          exerciseName: 'Overhead Extension Triceps',
          primaryMuscle: 'Triceps (Chef long)',
          targetMuscles: ['Triceps (Chef long)', 'Deltoïdes'],
          restSeconds: 75,
          sets: [
            { id: 's18', setNumber: 1, type: 'normal', weightKg: 20, reps: 12, rir: undefined, completed: false, previous: '20kg x 12' },
            { id: 's19', setNumber: 2, type: 'normal', weightKg: 24, reps: 10, rir: undefined, completed: false, previous: '24kg x 10' },
            { id: 's20', setNumber: 3, type: 'normal', weightKg: 24, reps: 9, rir: undefined, completed: false, previous: '24kg x 9' },
          ],
        },
        {
          id: 'ex_tpl_curl_pupitre',
          exerciseId: 'curl_pupitre_halteres',
          exerciseName: 'Curl Pupitre Haltères',
          primaryMuscle: 'Biceps',
          targetMuscles: ['Biceps brachial', 'Brachial antérieur'],
          restSeconds: 90,
          sets: [
            { id: 's21', setNumber: 1, type: 'failure', weightKg: 14, reps: 10, rir: undefined, completed: false, previous: '14kg x 10 (Échec)' },
            { id: 's22', setNumber: 2, type: 'failure', weightKg: 14, reps: 8, rir: undefined, completed: false, previous: '14kg x 8 (Échec)' },
          ],
        },
      ],
    },
    {
      id: 'tpl_circuit_abdos',
      title: 'Abdos',
      description: 'Séance abdos mixte combinant un circuit de 6 exercices et du travail de force avec Ab Rollout.',
      targetMuscles: ['Grand Droit', 'Obliques', 'Transverse / Gainage'],
      blocks: [
        {
          id: 'blk_circuit_abdos_1',
          type: 'circuit',
          title: 'Round',
          rounds: 3,
          restBetweenRoundsSeconds: 120,
          exercises: [
            {
              id: 'circ_ex_crunch_inverse',
              exerciseName: 'Crunch inversé',
              primaryMuscle: 'Grand droit de l\'abdomen',
              targetMuscles: ['Bas des abdos'],
              targetValue: 12,
              targetType: 'reps',
            },
            {
              id: 'circ_ex_foot_to_foot',
              exerciseName: 'Foot to foot',
              primaryMuscle: 'Obliques',
              targetMuscles: ['Obliques internes et externes'],
              targetValue: 10,
              targetType: 'reps',
            },
            {
              id: 'circ_ex_releve_genoux',
              exerciseName: 'Relevé de genoux suspendu',
              primaryMuscle: 'Bas des abdos',
              targetMuscles: ['Grand droit', 'Fléchisseurs de hanche'],
              targetValue: 10,
              targetType: 'reps',
            },
            {
              id: 'circ_ex_russian_twist',
              exerciseName: 'Russian Twist',
              primaryMuscle: 'Obliques',
              targetMuscles: ['Obliques', 'Sangle abdominale'],
              targetValue: 30,
              targetType: 'time',
            },
            {
              id: 'circ_ex_rowing_planche',
              exerciseName: 'Rowing planche',
              primaryMuscle: 'Gainage & Dos',
              targetMuscles: ['Transverse', 'Grand dorsal'],
              targetValue: 10,
              targetType: 'reps',
            },
            {
              id: 'circ_ex_gainage_commando',
              exerciseName: 'Gainage Commando',
              primaryMuscle: 'Gainage profond',
              targetMuscles: ['Transverse', 'Épaules'],
              targetValue: 45,
              targetType: 'time',
            },
          ],
        },
        {
          id: 'blk_single_ab_rollout',
          type: 'single',
          exercise: {
            id: 'ex_ab_rollout',
            exerciseId: 'ab_rollout',
            exerciseName: 'Ab rollout',
            primaryMuscle: 'Grand droit & Transverse',
            targetMuscles: ['Grand droit de l\'abdomen', 'Sangle abdominale profonde'],
            restSeconds: 90,
            sets: [
              {
                id: 'set_ab_rollout_1',
                setNumber: 1,
                type: 'normal',
                weightKg: 0,
                reps: 10,
                rir: undefined,
                completed: false,
                previous: '10 reps',
              },
            ],
          },
        },
      ],
    },
  ],
  history: [
    {
      id: 'sess_upper_b_aug7',
      title: 'Upper B',
      templateId: 'tpl_upper_b',
      startTime: '2026-08-07T17:30:00.000Z',
      endTime: '2026-08-07T18:45:00.000Z',
      durationSeconds: 4500,
      totalVolumeKg: 3840,
      completedSetsCount: 20,
      totalSetsCount: 20,
      status: 'completed',
      exercises: [
        {
          id: 'ex_hist_1',
          exerciseId: 'dips',
          exerciseName: 'Dips',
          primaryMuscle: 'Pectoraux & Triceps',
          targetMuscles: ['Pectoraux (Bas)', 'Triceps', 'Deltoïde antérieur'],
          restSeconds: 90,
          sets: [
            { id: 'hs1', setNumber: 1, type: 'normal', weightKg: 0, reps: 12, rir: 2, completed: true, completedAt: '2026-08-07T17:35:00.000Z' },
            { id: 'hs2', setNumber: 2, type: 'normal', weightKg: 10, reps: 10, rir: 1, completed: true, completedAt: '2026-08-07T17:38:00.000Z' },
            { id: 'hs3', setNumber: 3, type: 'normal', weightKg: 10, reps: 9, rir: 1, completed: true, completedAt: '2026-08-07T17:41:00.000Z' },
            { id: 'hs4', setNumber: 4, type: 'normal', weightKg: 10, reps: 8, rir: 0, completed: true, completedAt: '2026-08-07T17:44:00.000Z' },
          ],
        },
        {
          id: 'ex_hist_2',
          exerciseId: 'low_cable_fly',
          exerciseName: 'Low Cable Fly',
          primaryMuscle: 'Pectoraux',
          targetMuscles: ['Pectoraux (Haut & Médian)'],
          restSeconds: 75,
          sets: [
            { id: 'hs5', setNumber: 1, type: 'normal', weightKg: 12.5, reps: 12, rir: 2, completed: true, completedAt: '2026-08-07T17:48:00.000Z' },
            { id: 'hs6', setNumber: 2, type: 'normal', weightKg: 15, reps: 10, rir: 1, completed: true, completedAt: '2026-08-07T17:51:00.000Z' },
            { id: 'hs7', setNumber: 3, type: 'normal', weightKg: 15, reps: 10, rir: 0, completed: true, completedAt: '2026-08-07T17:54:00.000Z' },
          ],
        },
      ],
    },
  ],
  measurements: [
    { id: 'm1', date: '2026-08-01', weightKg: 79.0, chestCm: 104, thighCm: 58, bicepsCm: 39 },
    { id: 'm2', date: '2026-08-08', weightKg: 78.5, chestCm: 104.5, thighCm: 58.5, bicepsCm: 39.2 },
  ],
  folders: [
    { id: 'fld_1', name: 'Mes Programmes', templateIds: ['tpl_upper_b', 'tpl_circuit_abdos'], isCollapsed: false },
  ],
};

