import { MuscleTarget } from './muscles';

export interface SharedExercise {
  id: string;
  name: string;
  primaryMuscle: string;
  primaryMuscles?: string[];
  targetMuscles: string[];
  defaultRestSeconds: number;
  category: 'Pectoraux' | 'Dos' | 'Épaules' | 'Bras' | 'Jambes' | 'Abdos';
  isCustom?: boolean;
  isBodyweight?: boolean;
  subRegion?: string;
  muscleTargets?: MuscleTarget[];
}

export const EXERCISE_DATABASE: SharedExercise[] = [
  // ---------------- PECTORAUX (13) ----------------
  {
    id: 'bench_press',
    name: 'Développé Couché Barre',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef sterno-costal (Médian)',
    targetMuscles: ["Triceps","Deltoïde Antérieur"],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef sterno-costal (Médian)', role: 'primary', fraction: 1.0 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Développé Couché Haltères',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef sterno-costal (Médian)',
    targetMuscles: ["Triceps","Deltoïde Antérieur"],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef sterno-costal (Médian)', role: 'primary', fraction: 1.0 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'incline_bench_press',
    name: 'Développé Incliné Barre',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef claviculaire (Haut)',
    targetMuscles: ["Deltoïde Antérieur","Triceps"],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef claviculaire (Haut)', role: 'primary', fraction: 1.0 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'incline_dumbbells',
    name: 'Développé Incliné Haltères',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef claviculaire (Haut)',
    targetMuscles: ["Deltoïde Antérieur","Triceps"],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef claviculaire (Haut)', role: 'primary', fraction: 1.0 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'decline_bench_press',
    name: 'Développé Décliné Barre',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef abdominal (Bas)',
    targetMuscles: ["Triceps"],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef abdominal (Bas)', role: 'primary', fraction: 1.0 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'chest_press_machine',
    name: 'Développé Couché Machine (Chest Press)',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef sterno-costal (Médian)',
    targetMuscles: ["Triceps"],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef sterno-costal (Médian)', role: 'primary', fraction: 1.0 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'dips',
    name: 'Dips',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef abdominal (Bas)',
    targetMuscles: ["Triceps","Deltoïde Antérieur"],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
    isBodyweight: true,
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef abdominal (Bas)', role: 'primary', fraction: 1.0 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'low_cable_fly',
    name: 'Low Cable Fly',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef claviculaire (Haut)',
    targetMuscles: [],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef claviculaire (Haut)', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'high_cable_fly',
    name: 'High Cable Fly',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef abdominal (Bas)',
    targetMuscles: [],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef abdominal (Bas)', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck / Écarté Machine',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef sterno-costal (Médian)',
    targetMuscles: ["Deltoïde Antérieur"],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef sterno-costal (Médian)', role: 'primary', fraction: 1.0 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'pushups',
    name: 'Pompes (Push-ups)',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef sterno-costal (Médian)',
    targetMuscles: ["Triceps","Deltoïde Antérieur"],
    defaultRestSeconds: 60,
    category: 'Pectoraux',
    isBodyweight: true,
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef sterno-costal (Médian)', role: 'primary', fraction: 1.0 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'landmine_press',
    name: 'Landmine Press',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef claviculaire (Haut)',
    targetMuscles: ["Deltoïde Antérieur","Triceps"],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef claviculaire (Haut)', role: 'primary', fraction: 1.0 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'pull_over_dumbbell',
    name: 'Pull-Over Haltères',
    primaryMuscle: 'Pectoraux',
    primaryMuscles: ["Pectoraux"],
    subRegion: 'Chef sterno-costal (Médian)',
    targetMuscles: ["Grand Dorsal","Triceps"],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
    muscleTargets: [
      { muscle: 'Pectoraux', subRegion: 'Chef sterno-costal (Médian)', role: 'primary', fraction: 1.0 },
      { muscle: 'Grand Dorsal', role: 'secondary', fraction: 0.5 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  // ---------------- DOS (15) ----------------
  {
    id: 'pullups',
    name: 'Tractions Prise Pronation',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Grand Rond","Biceps","Trapèzes"],
    defaultRestSeconds: 90,
    category: 'Dos',
    isBodyweight: true,
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Grand Rond', role: 'secondary', fraction: 0.5 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'chinups',
    name: 'Tractions Prise Supination',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Biceps","Grand Rond"],
    defaultRestSeconds: 90,
    category: 'Dos',
    isBodyweight: true,
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Grand Rond', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'lat_pulldown',
    name: 'Tirage Vertical Poulie Haute',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Grand Rond","Biceps","Trapèzes"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Grand Rond', role: 'secondary', fraction: 0.5 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'lat_pulldown_supination',
    name: 'Tirage Vertical Prise Supination',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Biceps","Grand Rond"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Grand Rond', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'tirage_vertical_neutre',
    name: 'Tirage Vertical Prise Neutre',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Grand Rond","Avant-bras"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Grand Rond', role: 'secondary', fraction: 0.5 },
      { muscle: 'Avant-bras', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'barbell_row',
    name: 'Rowing Barre Penché',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Trapèzes","Rhomboïdes","Lombaires","Biceps"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Lombaires', role: 'secondary', fraction: 0.5 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'dumbbell_row',
    name: 'Rowing Unilatéral Haltère',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Trapèzes","Rhomboïdes","Biceps"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'cable_row_seated',
    name: 'Tirage Horizontal Poulie (Seated Row)',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    subRegion: 'Moyens',
    targetMuscles: ["Trapèzes","Rhomboïdes","Grand Rond","Biceps"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Grand Dorsal', subRegion: 'Moyens', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Grand Rond', role: 'secondary', fraction: 0.5 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'tirage_horiz_unilat',
    name: 'Tirage Horizontal Unilatéral',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Trapèzes","Rhomboïdes","Biceps"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 't_bar_row',
    name: 'Rowing T-Bar',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ["Grand Dorsal"],
    targetMuscles: ["Trapèzes","Rhomboïdes","Lombaires","Biceps"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Grand Dorsal', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Lombaires', role: 'secondary', fraction: 0.5 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'seal_row',
    name: 'Seal Row Barre / Haltères',
    primaryMuscle: 'Trapèzes',
    primaryMuscles: ["Trapèzes"],
    subRegion: 'Moyens',
    targetMuscles: ["Rhomboïdes","Grand Dorsal","Deltoïde Postérieur"],
    defaultRestSeconds: 90,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Trapèzes', subRegion: 'Moyens', role: 'primary', fraction: 1.0 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Grand Dorsal', role: 'secondary', fraction: 0.5 },
      { muscle: 'Deltoïde Postérieur', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'rowing_planche',
    name: 'Rowing Planche / Chest-Supported',
    primaryMuscle: 'Trapèzes',
    primaryMuscles: ["Trapèzes"],
    subRegion: 'Moyens',
    targetMuscles: ["Grand Dorsal","Rhomboïdes"],
    defaultRestSeconds: 75,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Trapèzes', subRegion: 'Moyens', role: 'primary', fraction: 1.0 },
      { muscle: 'Grand Dorsal', role: 'secondary', fraction: 0.5 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'deadlift',
    name: 'Soulevé de Terre (Deadlift)',
    primaryMuscle: 'Lombaires',
    primaryMuscles: ["Lombaires"],
    subRegion: 'Érecteurs du rachis',
    targetMuscles: ["Ischio-Jambiers","Fessiers","Quadriceps","Trapèzes","Adducteurs"],
    defaultRestSeconds: 120,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Lombaires', subRegion: 'Érecteurs du rachis', role: 'primary', fraction: 1.0 },
      { muscle: 'Ischio-Jambiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Quadriceps', role: 'secondary', fraction: 0.5 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Adducteurs', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'rack_pull',
    name: 'Rack Pull',
    primaryMuscle: 'Lombaires',
    primaryMuscles: ["Lombaires"],
    subRegion: 'Érecteurs du rachis',
    targetMuscles: ["Trapèzes","Fessiers","Ischio-Jambiers"],
    defaultRestSeconds: 120,
    category: 'Dos',
    muscleTargets: [
      { muscle: 'Lombaires', subRegion: 'Érecteurs du rachis', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Ischio-Jambiers', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'hyperextensions',
    name: 'Hyperextensions / Banc à Lombaires',
    primaryMuscle: 'Lombaires',
    primaryMuscles: ["Lombaires"],
    subRegion: 'Érecteurs du rachis',
    targetMuscles: ["Fessiers","Ischio-Jambiers"],
    defaultRestSeconds: 60,
    category: 'Dos',
    isBodyweight: true,
    muscleTargets: [
      { muscle: 'Lombaires', subRegion: 'Érecteurs du rachis', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Ischio-Jambiers', role: 'secondary', fraction: 0.5 },
    ],
  },
  // ---------------- ÉPAULES (12) ----------------
  {
    id: 'overhead_press',
    name: 'Développé Militaire Barre (OHP)',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ["Deltoïde Antérieur"],
    targetMuscles: ["Deltoïde Latéral","Triceps"],
    defaultRestSeconds: 90,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Antérieur', role: 'primary', fraction: 1.0 },
      { muscle: 'Deltoïde Latéral', role: 'secondary', fraction: 0.5 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Développé Épaules Haltères',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ["Deltoïde Antérieur"],
    targetMuscles: ["Deltoïde Latéral","Triceps"],
    defaultRestSeconds: 90,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Antérieur', role: 'primary', fraction: 1.0 },
      { muscle: 'Deltoïde Latéral', role: 'secondary', fraction: 0.5 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'military_press_machine',
    name: 'Développé Épaules Machine',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ["Deltoïde Antérieur"],
    targetMuscles: ["Triceps"],
    defaultRestSeconds: 75,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Antérieur', role: 'primary', fraction: 1.0 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press Haltères',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ["Deltoïde Antérieur"],
    targetMuscles: ["Deltoïde Latéral","Triceps"],
    defaultRestSeconds: 90,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Antérieur', role: 'primary', fraction: 1.0 },
      { muscle: 'Deltoïde Latéral', role: 'secondary', fraction: 0.5 },
      { muscle: 'Triceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'elevations_lat_poulie',
    name: 'Élévations Latérales Poulie',
    primaryMuscle: 'Deltoïde Latéral',
    primaryMuscles: ["Deltoïde Latéral"],
    targetMuscles: ["Trapèzes"],
    defaultRestSeconds: 60,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Latéral', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'dumbbell_lateral_raise',
    name: 'Élévations Latérales Haltères',
    primaryMuscle: 'Deltoïde Latéral',
    primaryMuscles: ["Deltoïde Latéral"],
    targetMuscles: ["Trapèzes"],
    defaultRestSeconds: 60,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Latéral', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'front_raise',
    name: 'Élévations Frontales Haltères',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ["Deltoïde Antérieur"],
    targetMuscles: ["Pectoraux"],
    defaultRestSeconds: 60,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Antérieur', role: 'primary', fraction: 1.0 },
      { muscle: 'Pectoraux', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'upright_row',
    name: 'Tirage Menton Barre / Poulie',
    primaryMuscle: 'Deltoïde Latéral',
    primaryMuscles: ["Deltoïde Latéral"],
    targetMuscles: ["Trapèzes","Biceps"],
    defaultRestSeconds: 75,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Latéral', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'oiseau_poulie_unilat',
    name: 'Oiseau à la Poulie Unilatéral',
    primaryMuscle: 'Deltoïde Postérieur',
    primaryMuscles: ["Deltoïde Postérieur"],
    targetMuscles: ["Trapèzes","Rhomboïdes"],
    defaultRestSeconds: 60,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Postérieur', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'reverse_fly_machine',
    name: 'Oiseau Machine (Reverse Fly)',
    primaryMuscle: 'Deltoïde Postérieur',
    primaryMuscles: ["Deltoïde Postérieur"],
    targetMuscles: ["Trapèzes","Rhomboïdes"],
    defaultRestSeconds: 60,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Postérieur', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
      { muscle: 'Rhomboïdes', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'face_pull',
    name: 'Face Pull Poulie',
    primaryMuscle: 'Deltoïde Postérieur',
    primaryMuscles: ["Deltoïde Postérieur"],
    targetMuscles: ["Trapèzes"],
    defaultRestSeconds: 60,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Deltoïde Postérieur', role: 'primary', fraction: 1.0 },
      { muscle: 'Trapèzes', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'shrugs',
    name: 'Shrugs Haltères / Barre',
    primaryMuscle: 'Trapèzes',
    primaryMuscles: ["Trapèzes"],
    subRegion: 'Supérieurs',
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Épaules',
    muscleTargets: [
      { muscle: 'Trapèzes', subRegion: 'Supérieurs', role: 'primary', fraction: 1.0 },
    ],
  },
  // ---------------- BRAS (14) ----------------
  {
    id: 'barbell_curl',
    name: 'Curl Barre EZ',
    primaryMuscle: 'Biceps',
    primaryMuscles: ["Biceps"],
    subRegion: 'Chef court',
    targetMuscles: ["Avant-bras"],
    defaultRestSeconds: 75,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Biceps', subRegion: 'Chef court', role: 'primary', fraction: 1.0 },
      { muscle: 'Avant-bras', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'curl_pupitre_ez',
    name: 'Curl Pupitre Barre EZ (Larry Scott)',
    primaryMuscle: 'Biceps',
    primaryMuscles: ["Biceps"],
    subRegion: 'Chef court',
    targetMuscles: ["Avant-bras"],
    defaultRestSeconds: 75,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Biceps', subRegion: 'Chef court', role: 'primary', fraction: 1.0 },
      { muscle: 'Avant-bras', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'curl_pupitre_halteres',
    name: 'Curl Pupitre Haltères',
    primaryMuscle: 'Biceps',
    primaryMuscles: ["Biceps"],
    subRegion: 'Chef court',
    targetMuscles: ["Avant-bras"],
    defaultRestSeconds: 90,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Biceps', subRegion: 'Chef court', role: 'primary', fraction: 1.0 },
      { muscle: 'Avant-bras', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'dumbbell_curl',
    name: 'Curl Haltères Supination',
    primaryMuscle: 'Biceps',
    primaryMuscles: ["Biceps"],
    targetMuscles: ["Avant-bras"],
    defaultRestSeconds: 75,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Biceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Avant-bras', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'hammer_curl',
    name: 'Curl Marteau (Hammer Curl)',
    primaryMuscle: 'Avant-bras',
    primaryMuscles: ["Avant-bras"],
    subRegion: 'Brachioradial',
    targetMuscles: ["Biceps"],
    defaultRestSeconds: 75,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Avant-bras', subRegion: 'Brachioradial', role: 'primary', fraction: 1.0 },
      { muscle: 'Biceps', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Curl Incliné Haltères',
    primaryMuscle: 'Biceps',
    primaryMuscles: ["Biceps"],
    subRegion: 'Chef long',
    targetMuscles: [],
    defaultRestSeconds: 75,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Biceps', subRegion: 'Chef long', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'cable_curl',
    name: 'Curl Poulie Basse',
    primaryMuscle: 'Biceps',
    primaryMuscles: ["Biceps"],
    subRegion: 'Chef court',
    targetMuscles: ["Avant-bras"],
    defaultRestSeconds: 60,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Biceps', subRegion: 'Chef court', role: 'primary', fraction: 1.0 },
      { muscle: 'Avant-bras', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'concentration_curl',
    name: 'Curl Concentré Haltère',
    primaryMuscle: 'Biceps',
    primaryMuscles: ["Biceps"],
    subRegion: 'Chef court',
    targetMuscles: ["Avant-bras"],
    defaultRestSeconds: 60,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Biceps', subRegion: 'Chef court', role: 'primary', fraction: 1.0 },
      { muscle: 'Avant-bras', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'triceps_pushdown',
    name: 'Extension Triceps Poulie Haute',
    primaryMuscle: 'Triceps',
    primaryMuscles: ["Triceps"],
    subRegion: 'Chef latéral',
    targetMuscles: [],
    defaultRestSeconds: 75,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Triceps', subRegion: 'Chef latéral', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'overhead_triceps',
    name: 'Overhead Extension Triceps Poulie',
    primaryMuscle: 'Triceps',
    primaryMuscles: ["Triceps"],
    subRegion: 'Chef long',
    targetMuscles: [],
    defaultRestSeconds: 75,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Triceps', subRegion: 'Chef long', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'skullcrusher',
    name: 'Barre au Front (Skullcrusher)',
    primaryMuscle: 'Triceps',
    primaryMuscles: ["Triceps"],
    subRegion: 'Chef long',
    targetMuscles: [],
    defaultRestSeconds: 90,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Triceps', subRegion: 'Chef long', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'close_grip_bench_press',
    name: 'Développé Couché Prise Serrée',
    primaryMuscle: 'Triceps',
    primaryMuscles: ["Triceps"],
    subRegion: 'Chef latéral',
    targetMuscles: ["Pectoraux","Deltoïde Antérieur"],
    defaultRestSeconds: 90,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Triceps', subRegion: 'Chef latéral', role: 'primary', fraction: 1.0 },
      { muscle: 'Pectoraux', role: 'secondary', fraction: 0.5 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'triceps_dips_bench',
    name: 'Dips sur Banc (Bench Dips)',
    primaryMuscle: 'Triceps',
    primaryMuscles: ["Triceps"],
    targetMuscles: ["Deltoïde Antérieur"],
    defaultRestSeconds: 60,
    category: 'Bras',
    isBodyweight: true,
    muscleTargets: [
      { muscle: 'Triceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Deltoïde Antérieur', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'triceps_kickback',
    name: 'Kickback Triceps Haltère',
    primaryMuscle: 'Triceps',
    primaryMuscles: ["Triceps"],
    subRegion: 'Chef latéral',
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Bras',
    muscleTargets: [
      { muscle: 'Triceps', subRegion: 'Chef latéral', role: 'primary', fraction: 1.0 },
    ],
  },
  // ---------------- JAMBES (16) ----------------
  {
    id: 'squat',
    name: 'Squat Barre Arrière (Back Squat)',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: ["Fessiers","Adducteurs","Lombaires"],
    defaultRestSeconds: 120,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Adducteurs', role: 'secondary', fraction: 0.5 },
      { muscle: 'Lombaires', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'front_squat',
    name: 'Squat Barre Avant (Front Squat)',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: ["Fessiers","Abdominaux"],
    defaultRestSeconds: 120,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Abdominaux', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'belt_squat',
    name: 'Belt Squat',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: ["Fessiers","Adducteurs"],
    defaultRestSeconds: 120,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Adducteurs', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat Machine',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: ["Fessiers"],
    defaultRestSeconds: 90,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'leg_press',
    name: 'Presse à Cuisses',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: ["Fessiers","Ischio-Jambiers"],
    defaultRestSeconds: 90,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Ischio-Jambiers', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'romanian_deadlift',
    name: 'Soulevé de Terre Roumain (RDL)',
    primaryMuscle: 'Ischio-Jambiers',
    primaryMuscles: ["Ischio-Jambiers"],
    targetMuscles: ["Fessiers","Lombaires"],
    defaultRestSeconds: 90,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Ischio-Jambiers', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Lombaires', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Fentes Bulgares Haltères',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: ["Fessiers","Ischio-Jambiers"],
    defaultRestSeconds: 90,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Ischio-Jambiers', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'lunges',
    name: 'Fentes Marchées Haltères',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: ["Fessiers","Mollets"],
    defaultRestSeconds: 90,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Mollets', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension Machine',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: [],
    defaultRestSeconds: 75,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl Allongé / Assis',
    primaryMuscle: 'Ischio-Jambiers',
    primaryMuscles: ["Ischio-Jambiers"],
    targetMuscles: ["Mollets"],
    defaultRestSeconds: 75,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Ischio-Jambiers', role: 'primary', fraction: 1.0 },
      { muscle: 'Mollets', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'machine_adducteurs',
    name: 'Adducteurs à la Machine',
    primaryMuscle: 'Adducteurs',
    primaryMuscles: ["Adducteurs"],
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Adducteurs', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'machine_abducteurs',
    name: 'Abducteurs à la Machine',
    primaryMuscle: 'Fessiers',
    primaryMuscles: ["Fessiers"],
    subRegion: 'Moyen Fessier',
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Fessiers', subRegion: 'Moyen Fessier', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust Barre / Machine',
    primaryMuscle: 'Fessiers',
    primaryMuscles: ["Fessiers"],
    subRegion: 'Grand Fessier',
    targetMuscles: ["Ischio-Jambiers"],
    defaultRestSeconds: 90,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Fessiers', subRegion: 'Grand Fessier', role: 'primary', fraction: 1.0 },
      { muscle: 'Ischio-Jambiers', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat Haltère / KB',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ["Quadriceps"],
    targetMuscles: ["Fessiers","Abdominaux"],
    defaultRestSeconds: 75,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Quadriceps', role: 'primary', fraction: 1.0 },
      { muscle: 'Fessiers', role: 'secondary', fraction: 0.5 },
      { muscle: 'Abdominaux', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'calf_raises',
    name: 'Mollets Debout à la Machine',
    primaryMuscle: 'Mollets',
    primaryMuscles: ["Mollets"],
    subRegion: 'Gastrocnémiens',
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Mollets', subRegion: 'Gastrocnémiens', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'seated_calf_raise',
    name: 'Mollets Assis Machine',
    primaryMuscle: 'Mollets',
    primaryMuscles: ["Mollets"],
    subRegion: 'Soléaire',
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Jambes',
    muscleTargets: [
      { muscle: 'Mollets', subRegion: 'Soléaire', role: 'primary', fraction: 1.0 },
    ],
  },
  // ---------------- ABDOS (9) ----------------
  {
    id: 'crunch',
    name: 'Crunch',
    primaryMuscle: 'Abdominaux',
    primaryMuscles: ["Abdominaux"],
    subRegion: 'Partie haute',
    targetMuscles: [],
    defaultRestSeconds: 0,
    category: 'Abdos',
    muscleTargets: [
      { muscle: 'Abdominaux', subRegion: 'Partie haute', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'cable_crunch',
    name: 'Crunch Poulie Haute (Cable Crunch)',
    primaryMuscle: 'Abdominaux',
    primaryMuscles: ["Abdominaux"],
    subRegion: 'Partie haute',
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Abdos',
    muscleTargets: [
      { muscle: 'Abdominaux', subRegion: 'Partie haute', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'crunch_inverse',
    name: 'Crunch Inversé',
    primaryMuscle: 'Abdominaux',
    primaryMuscles: ["Abdominaux"],
    subRegion: 'Partie basse',
    targetMuscles: [],
    defaultRestSeconds: 0,
    category: 'Abdos',
    muscleTargets: [
      { muscle: 'Abdominaux', subRegion: 'Partie basse', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'foot_to_foot',
    name: 'Foot to Foot',
    primaryMuscle: 'Obliques',
    primaryMuscles: ["Obliques"],
    targetMuscles: ["Abdominaux"],
    defaultRestSeconds: 0,
    category: 'Abdos',
    muscleTargets: [
      { muscle: 'Obliques', role: 'primary', fraction: 1.0 },
      { muscle: 'Abdominaux', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'releve_jambes_bassin',
    name: 'Relevé de Jambes et de Bassin',
    primaryMuscle: 'Abdominaux',
    primaryMuscles: ["Abdominaux"],
    subRegion: 'Partie basse',
    targetMuscles: [],
    defaultRestSeconds: 0,
    category: 'Abdos',
    isBodyweight: true,
    muscleTargets: [
      { muscle: 'Abdominaux', subRegion: 'Partie basse', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'releve_genoux_suspendu',
    name: 'Relevé de Genoux Suspendu',
    primaryMuscle: 'Abdominaux',
    primaryMuscles: ["Abdominaux"],
    subRegion: 'Partie basse',
    targetMuscles: [],
    defaultRestSeconds: 0,
    category: 'Abdos',
    isBodyweight: true,
    muscleTargets: [
      { muscle: 'Abdominaux', subRegion: 'Partie basse', role: 'primary', fraction: 1.0 },
    ],
  },
  {
    id: 'planche_statique',
    name: 'Planche Statique',
    primaryMuscle: 'Abdominaux',
    primaryMuscles: ["Abdominaux"],
    subRegion: 'Transverse',
    targetMuscles: ["Lombaires"],
    defaultRestSeconds: 105,
    category: 'Abdos',
    muscleTargets: [
      { muscle: 'Abdominaux', subRegion: 'Transverse', role: 'primary', fraction: 1.0 },
      { muscle: 'Lombaires', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Roulette Abdominale (Ab Wheel)',
    primaryMuscle: 'Abdominaux',
    primaryMuscles: ["Abdominaux"],
    subRegion: 'Grand Droit',
    targetMuscles: ["Grand Dorsal"],
    defaultRestSeconds: 60,
    category: 'Abdos',
    muscleTargets: [
      { muscle: 'Abdominaux', subRegion: 'Grand Droit', role: 'primary', fraction: 1.0 },
      { muscle: 'Grand Dorsal', role: 'secondary', fraction: 0.5 },
    ],
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    primaryMuscle: 'Obliques',
    primaryMuscles: ["Obliques"],
    targetMuscles: ["Abdominaux"],
    defaultRestSeconds: 0,
    category: 'Abdos',
    muscleTargets: [
      { muscle: 'Obliques', role: 'primary', fraction: 1.0 },
      { muscle: 'Abdominaux', role: 'secondary', fraction: 0.5 },
    ],
  },
];
