export interface SharedExercise {
  id: string;
  name: string;
  primaryMuscle: string;
  primaryMuscles?: string[];
  targetMuscles: string[];
  defaultRestSeconds: number;
  category: 'Pectoraux' | 'Dos' | 'Épaules' | 'Bras' | 'Jambes' | 'Abdos';
  isCustom?: boolean;
}

export const EXERCISE_DATABASE: SharedExercise[] = [
  // ---------------- PECTORAUX (13) ----------------
  {
    id: 'bench_press',
    name: 'Développé Couché Barre',
    primaryMuscle: 'Pectoraux (Chef sterno-costal - Médian)',
    primaryMuscles: ['Pectoraux (Chef sterno-costal - Médian)'],
    targetMuscles: ['Triceps (Chef latéral)', 'Deltoïde antérieur'],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Développé Couché Haltères',
    primaryMuscle: 'Pectoraux (Chef sterno-costal - Médian)',
    primaryMuscles: ['Pectoraux (Chef sterno-costal - Médian)'],
    targetMuscles: ['Triceps (Chef latéral)', 'Deltoïde antérieur'],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
  },
  {
    id: 'incline_bench_press',
    name: 'Développé Incliné Barre',
    primaryMuscle: 'Pectoraux (Chef claviculaire - Haut)',
    primaryMuscles: ['Pectoraux (Chef claviculaire - Haut)'],
    targetMuscles: ['Deltoïde antérieur', 'Triceps (Chef latéral)'],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
  },
  {
    id: 'incline_dumbbells',
    name: 'Développé Incliné Haltères',
    primaryMuscle: 'Pectoraux (Chef claviculaire - Haut)',
    primaryMuscles: ['Pectoraux (Chef claviculaire - Haut)'],
    targetMuscles: ['Deltoïde antérieur', 'Triceps (Chef latéral)'],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
  },
  {
    id: 'decline_bench_press',
    name: 'Développé Décliné Barre',
    primaryMuscle: 'Pectoraux (Chef abdominal - Bas)',
    primaryMuscles: ['Pectoraux (Chef abdominal - Bas)'],
    targetMuscles: ['Triceps (Chef latéral)'],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
  },
  {
    id: 'chest_press_machine',
    name: 'Développé Couché Machine (Chest Press)',
    primaryMuscle: 'Pectoraux (Chef sterno-costal - Médian)',
    primaryMuscles: ['Pectoraux (Chef sterno-costal - Médian)'],
    targetMuscles: ['Triceps (Chef latéral)'],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
  },
  {
    id: 'dips',
    name: 'Dips (Pectoraux & Triceps)',
    primaryMuscle: 'Pectoraux (Chef abdominal - Bas), Triceps (Chef latéral)',
    primaryMuscles: ['Pectoraux (Chef abdominal - Bas)', 'Triceps (Chef latéral)'],
    targetMuscles: ['Deltoïde antérieur'],
    defaultRestSeconds: 90,
    category: 'Pectoraux',
  },
  {
    id: 'low_cable_fly',
    name: 'Low Cable Fly (Poulie Basse)',
    primaryMuscle: 'Pectoraux (Chef claviculaire - Haut)',
    primaryMuscles: ['Pectoraux (Chef claviculaire - Haut)'],
    targetMuscles: ['Pectoraux (Chef sterno-costal - Médian)'],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
  },
  {
    id: 'high_cable_fly',
    name: 'High Cable Fly (Poulie Haute)',
    primaryMuscle: 'Pectoraux (Chef abdominal - Bas)',
    primaryMuscles: ['Pectoraux (Chef abdominal - Bas)'],
    targetMuscles: ['Pectoraux (Chef sterno-costal - Médian)'],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck / Écarté Machine',
    primaryMuscle: 'Pectoraux (Chef sterno-costal - Médian)',
    primaryMuscles: ['Pectoraux (Chef sterno-costal - Médian)'],
    targetMuscles: ['Deltoïde antérieur'],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
  },
  {
    id: 'pushups',
    name: 'Pompes (Push-ups)',
    primaryMuscle: 'Pectoraux (Chef sterno-costal - Médian), Triceps (Chef latéral)',
    primaryMuscles: ['Pectoraux (Chef sterno-costal - Médian)', 'Triceps (Chef latéral)'],
    targetMuscles: ['Deltoïde antérieur', 'Transverse'],
    defaultRestSeconds: 60,
    category: 'Pectoraux',
  },
  {
    id: 'landmine_press',
    name: 'Landmine Press',
    primaryMuscle: 'Pectoraux (Chef claviculaire - Haut)',
    primaryMuscles: ['Pectoraux (Chef claviculaire - Haut)'],
    targetMuscles: ['Deltoïde antérieur', 'Triceps (Chef latéral)'],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
  },
  {
    id: 'pull_over_dumbbell',
    name: 'Pull-Over Haltères',
    primaryMuscle: 'Pectoraux (Chef sterno-costal - Médian), Grand Dorsal',
    primaryMuscles: ['Pectoraux (Chef sterno-costal - Médian)', 'Grand Dorsal'],
    targetMuscles: ['Triceps (Chef long)', 'Dentelé antérieur'],
    defaultRestSeconds: 75,
    category: 'Pectoraux',
  },

  // ---------------- DOS (15) ----------------
  {
    id: 'pullups',
    name: 'Tractions Prise Pronation',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ['Grand Dorsal'],
    targetMuscles: ['Grand Rond', 'Biceps (Chef court)', 'Trapèzes (Inférieurs)'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'chinups',
    name: 'Tractions Prise Supination',
    primaryMuscle: 'Grand Dorsal, Biceps (Chef court)',
    primaryMuscles: ['Grand Dorsal', 'Biceps (Chef court)'],
    targetMuscles: ['Brachial', 'Grand Rond'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'lat_pulldown',
    name: 'Tirage Vertical Poulie Haute',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ['Grand Dorsal'],
    targetMuscles: ['Grand Rond', 'Biceps (Chef court)', 'Trapèzes (Inférieurs)'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'lat_pulldown_supination',
    name: 'Tirage Vertical Prise Supination',
    primaryMuscle: 'Grand Dorsal, Biceps (Chef court)',
    primaryMuscles: ['Grand Dorsal', 'Biceps (Chef court)'],
    targetMuscles: ['Brachial', 'Grand Rond'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'tirage_vertical_neutre',
    name: 'Tirage Vertical Prise Neutre',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ['Grand Dorsal'],
    targetMuscles: ['Grand Rond', 'Brachioradial'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'barbell_row',
    name: 'Rowing Barre Penché',
    primaryMuscle: 'Grand Dorsal, Trapèzes (Moyens)',
    primaryMuscles: ['Grand Dorsal', 'Trapèzes (Moyens)'],
    targetMuscles: ['Rhomboïdes', 'Lombaires (Érecteurs du rachis)', 'Biceps (Chef court)'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'dumbbell_row',
    name: 'Rowing Unilatéral Haltère',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ['Grand Dorsal'],
    targetMuscles: ['Trapèzes (Moyens)', 'Rhomboïdes', 'Biceps (Chef court)'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'cable_row_seated',
    name: 'Tirage Horizontal Poulie (Seated Row)',
    primaryMuscle: 'Trapèzes (Moyens), Rhomboïdes, Grand Dorsal',
    primaryMuscles: ['Trapèzes (Moyens)', 'Rhomboïdes', 'Grand Dorsal'],
    targetMuscles: ['Grand Rond', 'Biceps (Chef court)'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'tirage_horiz_unilat',
    name: 'Tirage Horizontal Unilatéral',
    primaryMuscle: 'Grand Dorsal',
    primaryMuscles: ['Grand Dorsal'],
    targetMuscles: ['Trapèzes (Moyens)', 'Rhomboïdes', 'Biceps (Chef court)'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 't_bar_row',
    name: 'Rowing T-Bar',
    primaryMuscle: 'Trapèzes (Moyens), Rhomboïdes, Grand Dorsal',
    primaryMuscles: ['Trapèzes (Moyens)', 'Rhomboïdes', 'Grand Dorsal'],
    targetMuscles: ['Lombaires (Érecteurs du rachis)', 'Biceps (Chef court)'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'seal_row',
    name: 'Seal Row Barre / Haltères',
    primaryMuscle: 'Trapèzes (Moyens), Rhomboïdes',
    primaryMuscles: ['Trapèzes (Moyens)', 'Rhomboïdes'],
    targetMuscles: ['Grand Dorsal', 'Deltoïde Postérieur'],
    defaultRestSeconds: 90,
    category: 'Dos',
  },
  {
    id: 'rowing_planche',
    name: 'Rowing Planche / Chest-Supported',
    primaryMuscle: 'Trapèzes (Moyens), Grand Dorsal',
    primaryMuscles: ['Trapèzes (Moyens)', 'Grand Dorsal'],
    targetMuscles: ['Rhomboïdes', 'Transverse'],
    defaultRestSeconds: 75,
    category: 'Dos',
  },
  {
    id: 'deadlift',
    name: 'Soulevé de Terre (Deadlift)',
    primaryMuscle: 'Ischio-jambiers, Grand Fessier, Lombaires (Érecteurs du rachis)',
    primaryMuscles: ['Ischio-jambiers', 'Grand Fessier', 'Lombaires (Érecteurs du rachis)'],
    targetMuscles: ['Quadriceps', 'Trapèzes (Supérieurs)', 'Adducteurs'],
    defaultRestSeconds: 120,
    category: 'Dos',
  },
  {
    id: 'rack_pull',
    name: 'Rack Pull',
    primaryMuscle: 'Lombaires (Érecteurs du rachis), Trapèzes (Supérieurs)',
    primaryMuscles: ['Lombaires (Érecteurs du rachis)', 'Trapèzes (Supérieurs)'],
    targetMuscles: ['Grand Fessier', 'Ischio-jambiers'],
    defaultRestSeconds: 120,
    category: 'Dos',
  },
  {
    id: 'hyperextensions',
    name: 'Hyperextensions / Banc à Lombaires',
    primaryMuscle: 'Lombaires (Érecteurs du rachis), Grand Fessier',
    primaryMuscles: ['Lombaires (Érecteurs du rachis)', 'Grand Fessier'],
    targetMuscles: ['Ischio-jambiers'],
    defaultRestSeconds: 60,
    category: 'Dos',
  },

  // ---------------- ÉPAULES (12) ----------------
  {
    id: 'overhead_press',
    name: 'Développé Militaire Barre (OHP)',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ['Deltoïde Antérieur'],
    targetMuscles: ['Deltoïde Latéral', 'Triceps (Chef latéral)'],
    defaultRestSeconds: 90,
    category: 'Épaules',
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Développé Épaules Haltères',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ['Deltoïde Antérieur'],
    targetMuscles: ['Deltoïde Latéral', 'Triceps (Chef latéral)'],
    defaultRestSeconds: 90,
    category: 'Épaules',
  },
  {
    id: 'military_press_machine',
    name: 'Développé Épaules Machine',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ['Deltoïde Antérieur'],
    targetMuscles: ['Triceps (Chef latéral)'],
    defaultRestSeconds: 75,
    category: 'Épaules',
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press Haltères',
    primaryMuscle: 'Deltoïde Antérieur, Deltoïde Latéral',
    primaryMuscles: ['Deltoïde Antérieur', 'Deltoïde Latéral'],
    targetMuscles: ['Triceps (Chef latéral)'],
    defaultRestSeconds: 90,
    category: 'Épaules',
  },
  {
    id: 'elevations_lat_poulie',
    name: 'Élévations Latérales Poulie',
    primaryMuscle: 'Deltoïde Latéral',
    primaryMuscles: ['Deltoïde Latéral'],
    targetMuscles: ['Trapèzes Supérieurs'],
    defaultRestSeconds: 60,
    category: 'Épaules',
  },
  {
    id: 'dumbbell_lateral_raise',
    name: 'Élévations Latérales Haltères',
    primaryMuscle: 'Deltoïde Latéral',
    primaryMuscles: ['Deltoïde Latéral'],
    targetMuscles: ['Trapèzes Supérieurs'],
    defaultRestSeconds: 60,
    category: 'Épaules',
  },
  {
    id: 'front_raise',
    name: 'Élévations Frontales Haltères',
    primaryMuscle: 'Deltoïde Antérieur',
    primaryMuscles: ['Deltoïde Antérieur'],
    targetMuscles: ['Pectoraux (Chef claviculaire - Haut)'],
    defaultRestSeconds: 60,
    category: 'Épaules',
  },
  {
    id: 'upright_row',
    name: 'Tirage Menton Barre / Poulie',
    primaryMuscle: 'Deltoïde Latéral, Trapèzes Supérieurs',
    primaryMuscles: ['Deltoïde Latéral', 'Trapèzes Supérieurs'],
    targetMuscles: ['Biceps (Chef court)'],
    defaultRestSeconds: 75,
    category: 'Épaules',
  },
  {
    id: 'oiseau_poulie_unilat',
    name: 'Oiseau à la Poulie Unilatéral',
    primaryMuscle: 'Deltoïde Postérieur',
    primaryMuscles: ['Deltoïde Postérieur'],
    targetMuscles: ['Rhomboïdes', 'Trapèzes (Moyens)'],
    defaultRestSeconds: 60,
    category: 'Épaules',
  },
  {
    id: 'reverse_fly_machine',
    name: 'Oiseau Machine (Reverse Fly)',
    primaryMuscle: 'Deltoïde Postérieur',
    primaryMuscles: ['Deltoïde Postérieur'],
    targetMuscles: ['Rhomboïdes', 'Trapèzes (Moyens)'],
    defaultRestSeconds: 60,
    category: 'Épaules',
  },
  {
    id: 'face_pull',
    name: 'Face Pull Poulie',
    primaryMuscle: 'Deltoïde Postérieur, Trapèzes (Moyens)',
    primaryMuscles: ['Deltoïde Postérieur', 'Trapèzes (Moyens)'],
    targetMuscles: ['Coiffe des rotateurs'],
    defaultRestSeconds: 60,
    category: 'Épaules',
  },
  {
    id: 'shrugs',
    name: 'Shrugs Haltères / Barre',
    primaryMuscle: 'Trapèzes Supérieurs',
    primaryMuscles: ['Trapèzes Supérieurs'],
    targetMuscles: ['Élévateur de la scapula'],
    defaultRestSeconds: 60,
    category: 'Épaules',
  },

  // ---------------- BRAS (15) ----------------
  {
    id: 'barbell_curl',
    name: 'Curl Barre EZ',
    primaryMuscle: 'Biceps (Chef court)',
    primaryMuscles: ['Biceps (Chef court)'],
    targetMuscles: ['Biceps (Chef long)', 'Brachial'],
    defaultRestSeconds: 75,
    category: 'Bras',
  },
  {
    id: 'curl_pupitre_ez',
    name: 'Curl Pupitre Barre EZ (Larry Scott)',
    primaryMuscle: 'Biceps (Chef court)',
    primaryMuscles: ['Biceps (Chef court)'],
    targetMuscles: ['Brachial'],
    defaultRestSeconds: 75,
    category: 'Bras',
  },
  {
    id: 'curl_pupitre_halteres',
    name: 'Curl Pupitre Haltères',
    primaryMuscle: 'Biceps (Chef court)',
    primaryMuscles: ['Biceps (Chef court)'],
    targetMuscles: ['Brachial'],
    defaultRestSeconds: 90,
    category: 'Bras',
  },
  {
    id: 'dumbbell_curl',
    name: 'Curl Haltères Supination',
    primaryMuscle: 'Biceps (Chef court), Biceps (Chef long)',
    primaryMuscles: ['Biceps (Chef court)', 'Biceps (Chef long)'],
    targetMuscles: ['Brachial'],
    defaultRestSeconds: 75,
    category: 'Bras',
  },
  {
    id: 'hammer_curl',
    name: 'Curl Marteau (Hammer Curl)',
    primaryMuscle: 'Brachioradial, Brachial',
    primaryMuscles: ['Brachioradial', 'Brachial'],
    targetMuscles: ['Biceps (Chef long)'],
    defaultRestSeconds: 75,
    category: 'Bras',
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Curl Incliné Haltères',
    primaryMuscle: 'Biceps (Chef long)',
    primaryMuscles: ['Biceps (Chef long)'],
    targetMuscles: ['Biceps (Chef court)'],
    defaultRestSeconds: 75,
    category: 'Bras',
  },
  {
    id: 'cable_curl',
    name: 'Curl Poulie Basse',
    primaryMuscle: 'Biceps (Chef court)',
    primaryMuscles: ['Biceps (Chef court)'],
    targetMuscles: ['Brachial'],
    defaultRestSeconds: 60,
    category: 'Bras',
  },
  {
    id: 'concentration_curl',
    name: 'Curl Concentré Haltère',
    primaryMuscle: 'Biceps (Chef court)',
    primaryMuscles: ['Biceps (Chef court)'],
    targetMuscles: ['Brachial'],
    defaultRestSeconds: 60,
    category: 'Bras',
  },
  {
    id: 'triceps_pushdown',
    name: 'Extension Triceps Poulie Haute',
    primaryMuscle: 'Triceps (Chef latéral), Triceps (Chef médial)',
    primaryMuscles: ['Triceps (Chef latéral)', 'Triceps (Chef médial)'],
    targetMuscles: ['Triceps (Chef long)'],
    defaultRestSeconds: 75,
    category: 'Bras',
  },
  {
    id: 'triceps_rope_pushdown',
    name: 'Extension Triceps Corde Poulie',
    primaryMuscle: 'Triceps (Chef latéral), Triceps (Chef médial)',
    primaryMuscles: ['Triceps (Chef latéral)', 'Triceps (Chef médial)'],
    targetMuscles: ['Triceps (Chef long)'],
    defaultRestSeconds: 75,
    category: 'Bras',
  },
  {
    id: 'overhead_triceps',
    name: 'Overhead Extension Triceps Poulie',
    primaryMuscle: 'Triceps (Chef long)',
    primaryMuscles: ['Triceps (Chef long)'],
    targetMuscles: ['Triceps (Chef médial)'],
    defaultRestSeconds: 75,
    category: 'Bras',
  },
  {
    id: 'skullcrusher',
    name: 'Barre au Front (Skullcrusher)',
    primaryMuscle: 'Triceps (Chef long), Triceps (Chef médial)',
    primaryMuscles: ['Triceps (Chef long)', 'Triceps (Chef médial)'],
    targetMuscles: ['Triceps (Chef latéral)'],
    defaultRestSeconds: 90,
    category: 'Bras',
  },
  {
    id: 'close_grip_bench_press',
    name: 'Développé Couché Prise Serrée',
    primaryMuscle: 'Triceps (Chef latéral), Pectoraux (Chef sterno-costal - Médian)',
    primaryMuscles: ['Triceps (Chef latéral)', 'Pectoraux (Chef sterno-costal - Médian)'],
    targetMuscles: ['Deltoïde antérieur'],
    defaultRestSeconds: 90,
    category: 'Bras',
  },
  {
    id: 'triceps_dips_bench',
    name: 'Dips sur Banc (Bench Dips)',
    primaryMuscle: 'Triceps (Chef latéral), Triceps (Chef médial)',
    primaryMuscles: ['Triceps (Chef latéral)', 'Triceps (Chef médial)'],
    targetMuscles: ['Deltoïde antérieur'],
    defaultRestSeconds: 60,
    category: 'Bras',
  },
  {
    id: 'triceps_kickback',
    name: 'Kickback Triceps Haltère',
    primaryMuscle: 'Triceps (Chef latéral)',
    primaryMuscles: ['Triceps (Chef latéral)'],
    targetMuscles: ['Triceps (Chef long)'],
    defaultRestSeconds: 60,
    category: 'Bras',
  },

  // ---------------- JAMBES (16) ----------------
  {
    id: 'squat',
    name: 'Squat Barre Arrière (Back Squat)',
    primaryMuscle: 'Quadriceps, Grand Fessier',
    primaryMuscles: ['Quadriceps', 'Grand Fessier'],
    targetMuscles: ['Adducteurs', 'Lombaires (Érecteurs du rachis)'],
    defaultRestSeconds: 120,
    category: 'Jambes',
  },
  {
    id: 'front_squat',
    name: 'Squat Barre Avant (Front Squat)',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ['Quadriceps'],
    targetMuscles: ['Grand Fessier', 'Transverse'],
    defaultRestSeconds: 120,
    category: 'Jambes',
  },
  {
    id: 'belt_squat',
    name: 'Belt Squat',
    primaryMuscle: 'Quadriceps, Grand Fessier',
    primaryMuscles: ['Quadriceps', 'Grand Fessier'],
    targetMuscles: ['Adducteurs'],
    defaultRestSeconds: 120,
    category: 'Jambes',
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat Machine',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ['Quadriceps'],
    targetMuscles: ['Grand Fessier'],
    defaultRestSeconds: 90,
    category: 'Jambes',
  },
  {
    id: 'leg_press',
    name: 'Presse à Cuisses',
    primaryMuscle: 'Quadriceps, Grand Fessier',
    primaryMuscles: ['Quadriceps', 'Grand Fessier'],
    targetMuscles: ['Ischio-jambiers'],
    defaultRestSeconds: 90,
    category: 'Jambes',
  },
  {
    id: 'romanian_deadlift',
    name: 'Soulevé de Terre Roumain (RDL)',
    primaryMuscle: 'Ischio-jambiers, Grand Fessier',
    primaryMuscles: ['Ischio-jambiers', 'Grand Fessier'],
    targetMuscles: ['Lombaires (Érecteurs du rachis)'],
    defaultRestSeconds: 90,
    category: 'Jambes',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Fentes Bulgares Haltères',
    primaryMuscle: 'Quadriceps, Grand Fessier',
    primaryMuscles: ['Quadriceps', 'Grand Fessier'],
    targetMuscles: ['Moyen Fessier', 'Ischio-jambiers'],
    defaultRestSeconds: 90,
    category: 'Jambes',
  },
  {
    id: 'lunges',
    name: 'Fentes Marchées Haltères',
    primaryMuscle: 'Quadriceps, Grand Fessier',
    primaryMuscles: ['Quadriceps', 'Grand Fessier'],
    targetMuscles: ['Mollets (Soléaire)'],
    defaultRestSeconds: 90,
    category: 'Jambes',
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension Machine',
    primaryMuscle: 'Quadriceps',
    primaryMuscles: ['Quadriceps'],
    targetMuscles: [],
    defaultRestSeconds: 75,
    category: 'Jambes',
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl Allongé / Assis',
    primaryMuscle: 'Ischio-jambiers',
    primaryMuscles: ['Ischio-jambiers'],
    targetMuscles: ['Mollets (Gastrocnémiens)'],
    defaultRestSeconds: 75,
    category: 'Jambes',
  },
  {
    id: 'machine_adducteurs',
    name: 'Adducteurs à la Machine',
    primaryMuscle: 'Adducteurs',
    primaryMuscles: ['Adducteurs'],
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Jambes',
  },
  {
    id: 'machine_abducteurs',
    name: 'Abducteurs à la Machine',
    primaryMuscle: 'Moyen Fessier',
    primaryMuscles: ['Moyen Fessier'],
    targetMuscles: ['Grand Fessier'],
    defaultRestSeconds: 60,
    category: 'Jambes',
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust Barre / Machine',
    primaryMuscle: 'Grand Fessier',
    primaryMuscles: ['Grand Fessier'],
    targetMuscles: ['Ischio-jambiers'],
    defaultRestSeconds: 90,
    category: 'Jambes',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat Haltère / KB',
    primaryMuscle: 'Quadriceps, Grand Fessier',
    primaryMuscles: ['Quadriceps', 'Grand Fessier'],
    targetMuscles: ['Transverse'],
    defaultRestSeconds: 75,
    category: 'Jambes',
  },
  {
    id: 'calf_raises',
    name: 'Mollets Debout à la Machine',
    primaryMuscle: 'Mollets (Gastrocnémiens)',
    primaryMuscles: ['Mollets (Gastrocnémiens)'],
    targetMuscles: ['Mollets (Soléaire)'],
    defaultRestSeconds: 60,
    category: 'Jambes',
  },
  {
    id: 'seated_calf_raise',
    name: 'Mollets Assis Machine',
    primaryMuscle: 'Mollets (Soléaire)',
    primaryMuscles: ['Mollets (Soléaire)'],
    targetMuscles: [],
    defaultRestSeconds: 60,
    category: 'Jambes',
  },

  // ---------------- ABDOS (9) ----------------
  {
    id: 'crunch',
    name: 'Crunch',
    primaryMuscle: 'Grand Droit (Partie haute)',
    primaryMuscles: ['Grand Droit (Partie haute)'],
    targetMuscles: ['Grand Droit'],
    defaultRestSeconds: 0,
    category: 'Abdos',
  },
  {
    id: 'cable_crunch',
    name: 'Crunch Poulie Haute (Cable Crunch)',
    primaryMuscle: 'Grand Droit (Partie haute)',
    primaryMuscles: ['Grand Droit (Partie haute)'],
    targetMuscles: ['Grand Droit'],
    defaultRestSeconds: 60,
    category: 'Abdos',
  },
  {
    id: 'crunch_inverse',
    name: 'Crunch Inversé',
    primaryMuscle: 'Grand Droit (Partie basse)',
    primaryMuscles: ['Grand Droit (Partie basse)'],
    targetMuscles: ['Transverse'],
    defaultRestSeconds: 0,
    category: 'Abdos',
  },
  {
    id: 'foot_to_foot',
    name: 'Foot to Foot',
    primaryMuscle: 'Obliques',
    primaryMuscles: ['Obliques'],
    targetMuscles: ['Grand Droit'],
    defaultRestSeconds: 0,
    category: 'Abdos',
  },
  {
    id: 'releve_jambes_bassin',
    name: 'Relevé de Jambes et de Bassin',
    primaryMuscle: 'Grand Droit (Partie basse)',
    primaryMuscles: ['Grand Droit (Partie basse)'],
    targetMuscles: ['Fléchisseurs de la hanche'],
    defaultRestSeconds: 0,
    category: 'Abdos',
  },
  {
    id: 'releve_genoux_suspendu',
    name: 'Relevé de Genoux Suspendu',
    primaryMuscle: 'Grand Droit (Partie basse)',
    primaryMuscles: ['Grand Droit (Partie basse)'],
    targetMuscles: ['Fléchisseurs de la hanche'],
    defaultRestSeconds: 0,
    category: 'Abdos',
  },
  {
    id: 'planche_statique',
    name: 'Planche Statique',
    primaryMuscle: 'Transverse',
    primaryMuscles: ['Transverse'],
    targetMuscles: ['Grand Droit', 'Lombaires (Érecteurs du rachis)'],
    defaultRestSeconds: 105,
    category: 'Abdos',
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Roulette Abdominale (Ab Wheel)',
    primaryMuscle: 'Grand Droit, Transverse',
    primaryMuscles: ['Grand Droit', 'Transverse'],
    targetMuscles: ['Grand Dorsal'],
    defaultRestSeconds: 60,
    category: 'Abdos',
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    primaryMuscle: 'Obliques',
    primaryMuscles: ['Obliques'],
    targetMuscles: ['Grand Droit'],
    defaultRestSeconds: 0,
    category: 'Abdos',
  },
];
